local builtin = require('telescope.builtin')
  
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-e>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end)
vim.keymap.set('n', '<C-o>', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<C-M-o>', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<leader>tk', builtin.keymaps, {})
